// apps/web/src/components/CollectionsList/CollectionListItem.svelte
<script lang="ts">
  import { Link } from 'svelte-navigator';
  import type { Collection } from 'private-notes-api';
  import api, { callApi } from '@/api';
  export let active = false;
  export let collection: Collection;

  $: promise = active
    ? callApi<Collection>(api.getCollection, collection.collectionId)
    : undefined;
</script>

<li>
  <Link to={`collection/${collection.collectionId}`}>{collection.name}</Link>

  {#await promise}
    <p>Loading...</p>
  {:then collection}
    <ul class="pl-4">
      {#each collection.notes as note (note.noteId)}
        <li>
          <Link to={`collection/${collection.collectionId}/note/${note.noteId}`}
            >{note.title}</Link
          >
        </li>
      {/each}
    </ul>
  {:catch}
    <p>Fetching collection details failed...</p>
  {/await}
</li>

// apps/web/src/components/collection-list-item.tsx
import { component$, useResource$, Resource } from '@builder.io/qwik';
import { getCollection } from '~/api';
import type { Collection } from '~/api/types';

interface CollectionListItemProps {
  collection: Collection;
  active: boolean;
}

const CollectionListItem = component$(
  ({ collection, active }: CollectionListItemProps) => {
    const collectionResource = useResource$<Collection>(
      async ({ track, cleanup }) => {
        const abortController = new AbortController();
        console.log('Running notes');
        track(() => active);
        cleanup(() => abortController.abort('cleanup'));
        return getCollection(collection.collectionId, abortController);
      },
    );

    return (
      <li>
        {collection.name}
        <Resource
          value={collectionResource}
          onPending={() => <div>Loading...</div>}
          onRejected={() => <div>Failed to load notes</div>}
          onResolved={({ notes }) => (
            <ul class="pl-4">
              {notes?.map((note) => (
                <li>{note.title}</li>
              ))}
            </ul>
          )}
        />
      </li>
    );
  },
);

export default CollectionListItem;
