// apps/web/src/routes/layout.tsx
import { component$, Slot } from '@builder.io/qwik';
import { loader$ } from '@builder.io/qwik-city';

export const useServerTimeLoader = loader$(() => {
  return {
    date: new Date().toISOString(),
  };
});

export default component$(() => {
  const serverTime = useServerTimeLoader();
  return (
    <>
      <main class="grow">
        <header class="flex bg-teal-300">
          <h1>
            <a href="/" target="_self" class="p-6">
              PrivateNotes
            </a>
          </h1>
        </header>
        <Slot />
      </main>

      <footer class="p-6 bg-teal-300">
        <div>Private notes v0.1.0</div>
        <div>{serverTime.value.date}</div>
      </footer>
    </>
  );
});

// apps/web/src/components/Layout.svelte
<header class="bg-purple-600 px-4 py-6">
  <h1>
    <a href="/" target="_self">PrivateNotes</a>
  </h1>
</header>

<div class="flex h-full bg-cyan-100">
  <aside class="basis-1/5 bg-amber-500 p-6">
    <slot name="aside" />
  </aside>

  <main class="basis-full flex flex-col basis-4/5 bg-green-300 p-6">
    <slot name="main" />
  </main>
</div>

<footer class="bg-purple-800 p-6">
  <div>{`PrivateNotes v${import.meta.env.VITE_APP_VERSION}`}</div>
</footer>
